NMBP/Project 1/NMBP_project1/Project1/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project1.Controllers
{
    public class SetupController : Controller
    {
        private BLL.Manager manager {get; set;} //= new BLL.Manager();

        public ActionResult Index()
        {
            Core.serverSetup serverSetup = new Core.serverSetup();
            {
                serverSetup.server = Session["server"].ToString();
                serverSetup.port = Session["port"].ToString();
                serverSetup.username = Session["username"].ToString();
                serverSetup.password = Session["password"].ToString();
                serverSetup.DB = Session["DB"].ToString();
            }
            Models.SetupModel setupModel = new Models.SetupModel();
            setupModel.setupData = serverSetup;

            return View(setupModel);
        }

        [HttpPost]
        public ActionResult Index(Models.SetupModel setupModel)
        {
            if (setupModel.movieName != null)
            {
                this.manager = new BLL.Manager(setSessionData(setupModel.setupData));
                var result = manager.addMovie(setupModel.movieName);
                setupModel.result = result;
                if (result.Equals("Zapis uspješno dodan")) setupModel.movieName = "";
            }
            setSessionData(setupModel.setupData);
            return View(setupModel);
        }

        private Core.serverSetup setSessionData(Core.serverSetup serverSetup)
        {
            Session["server"] = serverSetup.server;
            Session["port"] = serverSetup.port;
            Session["username"] = serverSetup.username;
            Session["password"] = serverSetup.password;
            Session["DB"] = serverSetup.DB;

            return serverSetup;
        }

    }
}

NMBP/Project 1/NMBP_project1/Project1/Views/Setup/Index.cshtml
@model Project1.Models.SetupModel

@using (Html.BeginForm("Index","Setup",FormMethod.Post))
{
<h2>Setup parametara za pristup bazi</h2>
<div>
<div>Server: @Html.TextBoxFor(x => x.setupData.server)</div>
<div>Port: @Html.TextBoxFor(x => x.setupData.port)</div>
<div>Username: @Html.TextBoxFor(x => x.setupData.username)</div>
<div>Password: @Html.TextBoxFor(x => x.setupData.password)</div>
<div>DB: @Html.TextBoxFor(x => x.setupData.DB)</div>
</div>
<div>
    <button name="sendQuery" id="btnSubmitSetup">Spremi podatke</button>
</div>

<h2>Unos novog filma</h2>

<div>Naziv filma:
@Html.TextBoxFor(x => x.movieName)
</div>
<div>
    <button name="sendQuery" id="btnSubmitMovie">Unesi film</button>
</div>
    <div>
    @{
    if (Model!=null && Model.result!=null)
    {
     @Model.result  
    }
    }
    </div>
}