NMBP/Project 1/NMBP_project1/Project1/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project1.Controllers
{
    public class StatsController : Controller
    {
        private BLL.Manager manager { get; set; } //= new BLL.Manager();

        public ActionResult Index()
        {
            Models.StatsModel analyseModel = new Models.StatsModel();
            analyseModel.startDate = DateTime.Today;
            analyseModel.endDate = DateTime.Today;
            return View(analyseModel);
        }

        [HttpPost]
        public ActionResult Index(Models.StatsModel analyseModel)
        {
            manager = new BLL.Manager(setSessionData());
            analyseModel.analyseResults = manager.getStatistics(analyseModel.startDate, analyseModel.endDate, analyseModel.isByHour);
            analyseModel.startDate = analyseModel.startDate;
            analyseModel.endDate = analyseModel.endDate;
            return View(analyseModel);
        }

        private Core.serverSetup setSessionData()
        {
            Core.serverSetup serverSetup = new Core.serverSetup();
            serverSetup.server = Session["server"].ToString();
            serverSetup.port = Session["port"].ToString();
            serverSetup.username = Session["username"].ToString();
            serverSetup.password = Session["password"].ToString();
            serverSetup.DB = Session["DB"].ToString();

            return serverSetup;
        }
    }
}

NMBP/Project 1/NMBP_project1/Project1/Views/Stats/Index.cshtml
<link href="../../Content/themes/base/jquery.ui.theme.css" rel="stylesheet" />
<script src="../../Scripts/jquery-ui-1.8.20.min.js"></script>

@model Project1.Models.StatsModel

<h2>Analiza</h2>

@using (Html.BeginForm("Index","Stats",FormMethod.Post))
{
<div class="item">Početni datum: @Html.TextBoxFor(x=>x.startDate, new { id = "startDate", @class = "jquery_datepicker", @Value = @Model.startDate.ToString("dd.MM.yyyy.")})</div>
<div class="item">Krajnji datum: @Html.TextBoxFor(x=>x.endDate, new { id = "endDate", @class = "jquery_datepicker", @Value = @Model.endDate.ToString("dd.MM.yyyy.")})</div>

<div class="item">
    Odaberi granulaciju:
    <div>
        @{
        @Html.RadioButtonFor(x=>x.isByHour, true, new { Checked = "checked" }) @:Po satu
        @Html.RadioButtonFor(x=>x.isByHour, false) @:Po danu
        }
    </div>
</div>

<div class="item">
    <button name="sendQuery" id="btnSubmitQuery">Pošalji upit</button>
</div>
}

@Html.Partial("ResultsAnalyse", Model)

<script>
    $(document).ready(function () {
        $("#startDate").datepicker({
            dateFormat: 'dd.mm.yyyy.'
        });
    });

    $(document).ready(function () {
        $("#endDate").datepicker({
            dateFormat: 'dd.mm.yyyy.'
        });
    });
</script>